quarkus.container-image.name=velociraptor
quarkus.docker.dockerfile-jvm-path=../Dockerfile.jvm
quarkus.package.jar.type=uber-jar
quarkus.log.level=INFO
quarkus.management.enabled=true
velociraptor.gtfs.source.path=../fixtures/gtfs-sample
velociraptor.raptor.servicedate.precompute=true
quarkus.s3.devservices.enabled=false
quarkus.s3.aws.region=eu-west-1
